version: '2'
services:
  caddy:
    image: abiosoft/caddy
    volumes:
      - 'caddyfile:/etc/caddy'
      - 'doc_root:/srv'
      - 'ssl_certs:/root/.caddy'
    ports:
      - ${http_port}:${http_port}
      - ${https_port}:${https_port}
    command: [sh, -c, "echo http://0.0.0.0 > /etc/caddy/Caddyfile && caddy --conf /etc/caddy/Caddyfile"]

volumes:
  caddyfile: 
    driver: ${volume_driver}
  doc_root: 
    driver: ${volume_driver}
  ssl_certs: 
    driver: ${volume_driver}
