version: '2'
catalog:
  name: "Caddy-Static-Site"
  version: "v0.0.1-rancher"
  description: "Launch Caddy For Hosting Static Sites"
  uuid: caddy-static-site
  minimum_rancher_version: v0.51.0
  questions:
    - variable: http_port
      description: "public port to access the WordPress site"
      label: "HTTP Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: https_port
      description: "public port to access the WordPress site"
      label: "HTTPS Public Port"
      required: true
      default: "443"
      type: "int"
    - variable: volume_driver
      description: "Volume driver to use with this service"
      label: "Volume driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
