---
name: Wordpress
description: |
  A Wordpress stack on docker using Caddy, PHP-FPM & MariaDB
version: 0.0.1-rancher1
category: CMS
maintainer: Alex Penketh
license: Apache2
projectURL: https://github.com/APenketh/rancher-cattle-catalog
